services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile.fe
    container_name: sagw-fe
    volumes:
      - .:/src
      - /src/node_modules

  be:
    build:
      context: .
      dockerfile: Dockerfile.be
    container_name: sagw-be
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    environment:
      ENV: sample
    env_file:
      - .env/.env.playwright

    # payload will be started by playwright-be.config.ts
    command: npm run test:be:native

  mongo:
    image: mongodb/mongodb-community-server:7.0.16-ubi8
    container_name: sagw-mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo-db-data:/data/db
      - ./mongo.conf:/etc/mongo.conf:ro
    ports:
      - "27017:27017"
    command: ["mongod", "--config", "/etc/mongo.conf"]

