# syntax=docker.io/docker/dockerfile:1.7-labs
# FROM node:22.14.0-bookworm
# WORKDIR /src
# COPY --exclude=node_modules --exclude=Dockerfile.testing --exclude=docker-compose.testing.yml . .
# RUN npm install

# !! KEEP IN SYNC WITH playwright IN PACKAGE.JSON
# RUN npx playwright@1.51.1 install --with-deps

# ATTENTION: This docker file uses node 22.x. Regularly check if node version changed.

# ATTENTION: If the docker image is changed here, it also needs to be changed in deploy-branch.yml and deploy-prod.yml

FROM mcr.microsoft.com/playwright:v1.51.1-noble
WORKDIR /src
COPY --exclude=node_modules . .
RUN npm install