/* eslint-disable sort-keys */
import {
  InterfaceRte1, InterfaceRte2,
} from '@/payload-types';

export const sampleRte1: InterfaceRte1['content'] = {
  root: {

    children: [

      {

        children: [

          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Text',
            type: 'text',
            version: 1,
          },

          {
            text: '­',
            type: 'unicode-char',
            version: 1,
          },

          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'With',
            type: 'text',
            version: 1,
          },

          {
            text: '­',
            type: 'unicode-char',
            version: 1,
          },

          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Soft',
            type: 'text',
            version: 1,
          },

          {
            text: '­',
            type: 'unicode-char',
            version: 1,
          },

          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Hypens',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        textFormat: 0,
        textStyle: '',
        type: 'paragraph',
        version: 1,
      },
    ],
    direction: 'ltr',
    format: '',
    indent: 0,
    type: 'root',
    version: 1,
  },
};

/*
Some Title

Some paragraph text with bold, italic, underline, strikethrough, subscript,
superscript, an external link and an internal link.

Ordered list
item 1
item 2
item 3
Unordered list
item 1
item 2
item 3
*/

export const sampleRte2: InterfaceRte2['content'] = {
  root: {
    children: [
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Ein neuer Name für den Preis und drei Preisträgerinnen das Wichtigste der Preisverleihung 2025 auf einen Blick. (h2)',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h2',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Erster Preis: Ein Schlaglicht auf die ',
            type: 'text',
            version: 1,

          },
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: '«Boys» an Bord d',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'er französischen ',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 2,
            mode: 'normal',
            style: '',
            text: 'Dampfschiffe (h3 after h2)',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: 'start',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h3',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Um dem in der Regel internationalen Tätigkeitsfeld der Forscher·innen gerecht zu werden, heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) überzeugten die Jury in diesem Jahr durch die hohe Qualität ihrer wissenschaftlichen Arbeit. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Im Zuge der ',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 8,
            mode: 'normal',
            style: '',
            text: 'Globalisierung und des damit verbundenen',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' intensiveren Seeverkehrs wurden die Dampfschiffe mit viel CO',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 32,
            mode: 'normal',
            style: '',
            text: '2',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' zum Schauplatz auf 90m',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 64,
            mode: 'normal',
            style: '',
            text: '2',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' von ausgeprägten Hierarchien zwischen den Passagieren aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem preisgekrönten Artikel hervorgeht, stellt das stereotype Bild des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wie durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, Schmuggel oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Im Zuge der Globalisierung und des damit verbundenen ',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'intensiveren Seeverkehrs',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 3,
            fields: {
              doc: {
                label: 'Home Page',
                relationTo: 'homePage',
                value: '68d6ad35361131db0550dcdc',
              },
              linkType: 'internal',
            },
            id: '68df9982ebe5d7e2208f182b',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' wurden die Dampfschiffe zum ',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 4,
            mode: 'normal',
            style: '',
            text: 'Schauplatz von ausgeprägten Hierarchien zwischen den Passagieren',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem preisgekrönten Artikel hervorgeht, stellt das stereotype Bild des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wie durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, ',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Schmuggel',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'link',
            version: 3,
            fields: {
              url: 'https://www.sagw.ch/',
              newTab: true,
              linkType: 'custom',
            },
            id: '68df9961ebe5d7e2208f182a',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Im Zuge der Globalisierung',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 2,
            mode: 'normal',
            style: '',
            text: ' und des damit verbunde',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'nen intensiveren Seeverkehrs (h3 before p)',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h3',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'wurden die Dampfschiffe zum Schauplatz von ausgeprägten Hierarchien zwischen den Passagieren aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem preisgekrönten Artikel hervorgeht, stellt das stereotype Bild des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wie durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, Schmuggel oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Alle Vorteile der Mitgliedschaft (h5 before ol)',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h5',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Um dem in der Regel',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 2,
                mode: 'normal',
                style: '',
                text: ' internationalen Tätigkeitsfeld',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' der Forscher·innen gerecht zu werden,',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 2,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 3,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'überzeugten die Jury in diesem Jahr durch die hohe Qualität ihrer wissenschaftlichen Arbeit. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 4,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Um dem in der Regel',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 2,
                mode: 'normal',
                style: '',
                text: ' internationalen Tätigkeitsfeld',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' der Forscher·innen gerecht zu werden,',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 5,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 6,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 7,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'überzeugten die Jury in diesem Jahr durch die hohe Qualität ihrer wissenschaftlichen Arbeit. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 8,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Um dem in der Regel',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 2,
                mode: 'normal',
                style: '',
                text: ' internationalen Tätigkeitsfeld',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' der Forscher·innen gerecht zu werden,',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 9,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 10,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 11,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'überzeugten die Jury in diesem Jahr durch die hohe Qualität ihrer wissenschaftlichen Arbeit. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 12,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'list',
        version: 1,
        listType: 'number',
        start: 1,
        tag: 'ol',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Im Zuge der Globalisierung und des damit verbundenen intensiveren Seeverkehrs wurden die Dampfschiffe zum Schauplatz von ausgeprägten Hierarchien zwischen den Passagieren aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem preisgekrönten Artikel hervorgeht, stellt das stereotype Bild des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wie durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, Schmuggel oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Erster Preis: Ein Schlaglicht auf die ',
            type: 'text',
            version: 1,

          },
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: '«Boys» an Bord d',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'er französischen ',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 2,
            mode: 'normal',
            style: '',
            text: 'Dampfschiffe (h3)',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: 'start',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h3',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Im Zuge der Globalisierung und des damit verbundenen intensiveren Seeverkehrs wurden die Dampfschiffe zum Schauplatz von ausgeprägten Hierarchien zwischen den Passagieren aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem preisgekrönten Artikel hervorgeht, stellt das stereotype Bild ',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: 'des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wi',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'e durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, Schmuggel oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos.Um dem in der Regel internationalen ',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 2,
            mode: 'normal',
            style: '',
            text: 'Tätigkeitsfeld der Forscher·innen gerecht zu werden',
            type: 'text',
            version: 1,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: '.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Alle Vorteile der Mitgliedschaft (h4 before ul)',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h4',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) überzeugten die Jury ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 2,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'in diesem Jahr durch die hohe Qualität ihrer wissenschaftlichen Arbeit. Im Zuge der Globalisierung.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 3,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'damit verbundenen intensiveren Seeverkehrs wurden die Dampfschiffe zum Schauplatz von ausgeprägten Hierarchien',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 4,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' zwischen den Passagieren aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 5,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'list',
        version: 1,
        listType: 'bullet',
        start: 1,
        tag: 'ul',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' preisgekrönten Artikel hervorgeht, stellt das stereotype Bild des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wie durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, Schmuggel oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Um dem in der Regel',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 2,
                mode: 'normal',
                style: '',
                text: ' internationalen Tätigkeitsfeld',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' der Forscher·innen gerecht zu werden,',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 2,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 3,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'überzeugten die Jury in diesem Jahr durch die hohe Qualität ihrer wissenschaftlichen Arbeit. ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 4,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Um dem in der Regel',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 2,
                mode: 'normal',
                style: '',
                text: ' internationalen Tätigkeitsfeld',
                type: 'text',
                version: 1,
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' der Forscher·innen gerecht zu werden,',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 5,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'heisst der einstige Nachwuchspreis der SAGW neu Early Career Award. Stéphanie Soubrier (Universität Genf), ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 6,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Madeline Woker (Collegium Helveticum / University of Sheffield) und Magdalena Breyer (Universität Basel) ',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 7,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'list',
        version: 1,
        listType: 'number',
        start: 1,
        tag: 'ol',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Im Zuge der Globalisierung und des damit verbundenen intensiveren Seeverkehrs wurden die Dampfschiffe zum Schauplatz von ausgeprägten Hierarchien zwischen den Passagieren aus den Metropolen und den «Boys» aus Übersee. Das kollektive Porträt, das aus dem preisgekrönten Artikel hervorgeht, stellt das stereotype Bild des verweiblichten und unterwürfigen Arbeiters in Frage. Soubrier zeigt, wie durch die Anstellung sowohl Widerstand als auch Mobilität der «Boys» ermöglicht wurden. Die Bemühungen der Reederei, Einwegreisen zwischen Kolonien und Metropolen sowie Desertion, Schmuggel oder die gewerkschaftliche Organisation zu unterbinden, blieben erfolglos. ',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
      },
      {
        children: [],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h2',
      },
    ],
    direction: 'ltr',
    format: '',
    indent: 0,
    type: 'root',
    version: 1,
  },
};

/*
Example for data privacy checkbox
*/

export const sampleRtePrivacyCheckbox: InterfaceRte2['content'] = {
  root: {
    children: [
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Ich habe die Hinweise zum ',
            type: 'text',
            version: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Datenschutz',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            fields: {
              doc: {
                label: 'Home Page',
                relationTo: 'homePage',
                value: '68c6f2a27b546854b2c701ff',
              },
              linkType: 'internal',
            },
            format: '',
            id: '68c7f8ebb2920188de8380de',
            indent: 0,
            type: 'link',
            version: 3,
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' gelesen und akzeptiere sie.',
            type: 'text',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        textFormat: 0,
        textStyle: '',
        type: 'paragraph',
        version: 1,
      },
    ],
    direction: 'ltr',
    format: '',
    indent: 0,
    type: 'root',
    version: 1,
  },
};
