export const allPageInvalidationLogs = ({
  isSagw,
  time,
}: {
  isSagw: boolean;
  time: number;
}): any[] => {
  if (isSagw) {
    return [
      '[CACHE] invalidating path: /de',
      '[CACHE] invalidating path: /en',
      '[CACHE] invalidating path: /fr',
      '[CACHE] invalidating path: /it',
      '[CACHE] invalidating path: /de/data-privacy-de',
      '[CACHE] invalidating path: /fr/data-privacy-fr',
      '[CACHE] invalidating path: /it/data-privacy-it',
      '[CACHE] invalidating path: /en/data-privacy-en',
      '[CACHE] invalidating path: /de/impressum-de',
      '[CACHE] invalidating path: /fr/impressum-fr',
      '[CACHE] invalidating path: /it/impressum-it',
      '[CACHE] invalidating path: /en/impressum-en',
      `[CACHE] invalidating path: /de/overview-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/magazine-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/magazine-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/news-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/news-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/detail-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/detail-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/national-dictionary-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/national-dictionary-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/publication-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/publication-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/institute-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/institute-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/project-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/project-1-${time}-it`,
      `[CACHE] invalidating path: /de/overview-1-${time}/event-1-${time}`,
      `[CACHE] invalidating path: /it/overview-1-${time}-it/event-1-${time}-it`,
    ];
  }

  return [
    `[CACHE] invalidating path: /de/tenant-${time}`,
    `[CACHE] invalidating path: /en/tenant-${time}-en`,
    `[CACHE] invalidating path: /fr/tenant-${time}-fr`,
    `[CACHE] invalidating path: /it/tenant-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/data-privacy-de`,
    `[CACHE] invalidating path: /fr/tenant-${time}-fr/data-privacy-fr`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/data-privacy-it`,
    `[CACHE] invalidating path: /en/tenant-${time}-en/data-privacy-en`,
    `[CACHE] invalidating path: /de/tenant-${time}/impressum-de`,
    `[CACHE] invalidating path: /fr/tenant-${time}-fr/impressum-fr`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/impressum-it`,
    `[CACHE] invalidating path: /en/tenant-${time}-en/impressum-en`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/magazine-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/magazine-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/news-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/news-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/detail-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/detail-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/national-dictionary-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/national-dictionary-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/publication-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/publication-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/institute-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/institute-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/project-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/project-2-${time}-it`,
    `[CACHE] invalidating path: /de/tenant-${time}/overview-2-${time}/event-2-${time}`,
    `[CACHE] invalidating path: /it/tenant-${time}-it/overview-2-${time}-it/event-2-${time}-it`,
  ];
};
