// plc
import { Users } from '@/collections/Plc/Users';
import { Images } from '@/collections/Plc/Images';
import { Videos } from '@/collections/Plc/Videos';
import { NetworkCategories } from '@/collections/Plc/NetworkCategories';
import { Documents } from '@/collections/Plc/Documents';
import { Projects } from '@/collections/Plc/Projects';
import { People } from '@/collections/Plc/People';
import { PublicationTopics } from '@/collections/Plc/PublicationTopics';
import { PublicationTypes } from '@/collections/Plc/PublicationTypes';
import { EventCategories } from '@/collections/Plc/EventCategories';
import { Tenants } from '@/collections/Plc/Tenants';
import { ZenodoDocuments } from '@/collections/Plc/ZenodoDocuments';
import { Forms } from '@/collections/Plc/Forms';
import autogeneratePagesIndex from '@/collections/Pages/autoGeneratedPagesIndex';
import {
  globalCollectionsSlugs, singletonSlugs,
} from '@/collections/Pages/constants';
import { Teams } from './Plc/Teams';

import {
  CollectionConfig, CollectionSlug,
} from 'payload';

// we want to define page slugs once. using the exported collections from this
// file would not work if we would like to import the collections into a block
// or collection -> circular reference or more specific, the collections would
// not be defined yet at the time of importing them into a block. That's why
// we do it this way.
// main reason for this was: we want to add colletions array to the link
// feature in rte. we can't import it from here.

export const plcCollections: CollectionConfig[] = [
  Images,
  Videos,
  NetworkCategories,
  Documents,
  ZenodoDocuments,
  Projects,
  People,
  Teams,
  PublicationTopics,
  PublicationTypes,
  EventCategories,
  Tenants,
  Users,
  Forms,
];

// payload collections config
export const collections = [

  // Auto-generated pages index
  ...autogeneratePagesIndex,

  // plc
  ...plcCollections,

];

// multitenant plugin collections config
export interface InterfaceTenantCollectionObject {
  isGlobal?: boolean;
}

const tenantsCollectionsObject: Record<string, InterfaceTenantCollectionObject> = {};

const singletonSlugsarray = singletonSlugs.map((slug) => slug.slug);
const globalsCollectionsSlugsarray = globalCollectionsSlugs.map((slug) => slug.slug);

collections.forEach((item) => {
  if (item.slug !== Tenants.slug && item.slug !== Users.slug) {
    if (singletonSlugsarray.includes(item.slug as CollectionSlug) || globalsCollectionsSlugsarray.includes(item.slug as CollectionSlug)) {
      tenantsCollectionsObject[item.slug] = {
        isGlobal: true,
      };
    } else {
      tenantsCollectionsObject[item.slug] = {};
    }
  }
});

export const tenantsCollections = tenantsCollectionsObject;
