
// !! AUTO-GENERATED by /src/collections/Pages/generatePayloadPageImports.ts !!

import { HomePage } from '@/collections/Pages/Singletons/Home';
import { ErrorPage } from '@/collections/Pages/Singletons/Error';
import { DataPrivacyPage } from '@/collections/Pages/Singletons/DataPrivacy';
import { ImpressumPage } from '@/collections/Pages/Singletons/Impressum';
import { MagazineDetailPage } from '@/collections/Pages/Sets/MagazineDetail';
import { OverviewPage } from '@/collections/Pages/Sets/Overview';
import { DetailPage } from '@/collections/Pages/Sets/Detail';
import { EventDetailPage } from '@/collections/Pages/Sets/EventDetail';
import { NewsDetailPage } from '@/collections/Pages/Sets/NewsDetail';
import { PublicationDetailPage } from '@/collections/Pages/Sets/PublicationDetail';
import { NationalDictionaryDetailPage } from '@/collections/Pages/Sets/NationalDictionaryDetail';
import { InstituteDetailPage } from '@/collections/Pages/Sets/InstituteDetail';
import { ProjectDetailPage } from '@/collections/Pages/Sets/ProjectDetail';

export default [
  HomePage,
  ErrorPage,
  DataPrivacyPage,
  ImpressumPage,
  MagazineDetailPage,
  OverviewPage,
  DetailPage,
  EventDetailPage,
  NewsDetailPage,
  PublicationDetailPage,
  NationalDictionaryDetailPage,
  InstituteDetailPage,
  ProjectDetailPage,
];
