/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    images: Image;
    networkCategories: NetworkCategory;
    faqItems: FaqItem;
    documents: Document;
    projects: Project;
    people: Person;
    instituteDetail: InstituteDetail;
    magazineDetail: MagazineDetail;
    videos: Video;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    networkCategories: NetworkCategoriesSelect<false> | NetworkCategoriesSelect<true>;
    faqItems: FaqItemsSelect<false> | FaqItemsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    instituteDetail: InstituteDetailSelect<false> | InstituteDetailSelect<true>;
    magazineDetail: MagazineDetailSelect<false> | MagazineDetailSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
    network: Network;
    promotion: Promotion;
    institutes: Institute;
    earlyCareerAward: EarlyCareerAward;
    activities: Activity;
    magazineOverview: MagazineOverview;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    network: NetworkSelect<false> | NetworkSelect<true>;
    promotion: PromotionSelect<false> | PromotionSelect<true>;
    institutes: InstitutesSelect<false> | InstitutesSelect<true>;
    earlyCareerAward: EarlyCareerAwardSelect<false> | EarlyCareerAwardSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    magazineOverview: MagazineOverviewSelect<false> | MagazineOverviewSelect<true>;
  };
  locale: 'de' | 'fr' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  elements?: ButtonGroup[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonGroup".
 */
export interface ButtonGroup {
  buttons?:
    | {
        button: InterfaceButton;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ButtonGroup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InterfaceButton".
 */
export interface InterfaceButton {
  primary: boolean;
  label: string;
  size?: ('small' | 'medium' | 'large') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networkCategories".
 */
export interface NetworkCategory {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems".
 */
export interface FaqItem {
  id: string;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  project?: (string | null) | Project;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: string;
  department: 'admin' | 'science' | 'com';
  prefix?: string | null;
  firstname: string;
  middleName?: string | null;
  lastname: string;
  function: string;
  mail: string;
  phone: string;
  image: string | Image;
  memberType: 'executiveBoard' | 'direction' | 'team';
  fullName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instituteDetail".
 */
export interface InstituteDetail {
  id: string;
  hero: {
    title: string;
    colorMode: 'white' | 'color';
    colorScheme?: ('bright' | 'dark') | null;
  };
  instituteDetails: {
    title: string;
    text: string;
    logo: string | Image;
    linkType: 'internal' | 'external';
    linkInternal?: {
      text: string;
      slug: string | Page;
      openInNewWindow?: boolean | null;
    };
    linkExternal?: {
      text: string;
      href: string;
      openInNewWindow?: boolean | null;
    };
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazineDetail".
 */
export interface MagazineDetail {
  id: string;
  overviewPageProps: {
    teaserText: string;
  };
  hero: {
    title: string;
    lead: string;
    author: string;
    date: string;
  };
  contentBlocks?:
    | (
        | {
            title?: string | null;
            text: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            alignement?: ('left' | 'center' | 'right') | null;
            image: string | Image;
            title: string;
            caption: string;
            credits: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            video: string | Video;
            title: string;
            caption: string;
            credits: string;
            stillImage: string | Image;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
      )[]
    | null;
  downloads: {
    downloads: (string | Document)[];
  };
  links?:
    | {
        text: string;
        href: string;
        openInNewWindow?: boolean | null;
        description: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'linkExternal';
      }[]
    | null;
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'images';
        value: string | Image;
      } | null)
    | ({
        relationTo: 'networkCategories';
        value: string | NetworkCategory;
      } | null)
    | ({
        relationTo: 'faqItems';
        value: string | FaqItem;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'people';
        value: string | Person;
      } | null)
    | ({
        relationTo: 'instituteDetail';
        value: string | InstituteDetail;
      } | null)
    | ({
        relationTo: 'magazineDetail';
        value: string | MagazineDetail;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  elements?:
    | T
    | {
        ButtonGroup?: T | ButtonGroupSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonGroup_select".
 */
export interface ButtonGroupSelect<T extends boolean = true> {
  buttons?:
    | T
    | {
        button?: T | InterfaceButtonSelect<T>;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InterfaceButton_select".
 */
export interface InterfaceButtonSelect<T extends boolean = true> {
  primary?: T;
  label?: T;
  size?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networkCategories_select".
 */
export interface NetworkCategoriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  department?: T;
  prefix?: T;
  firstname?: T;
  middleName?: T;
  lastname?: T;
  function?: T;
  mail?: T;
  phone?: T;
  image?: T;
  memberType?: T;
  fullName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instituteDetail_select".
 */
export interface InstituteDetailSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        colorMode?: T;
        colorScheme?: T;
      };
  instituteDetails?:
    | T
    | {
        title?: T;
        text?: T;
        logo?: T;
        linkType?: T;
        linkInternal?:
          | T
          | {
              text?: T;
              slug?: T;
              openInNewWindow?: T;
            };
        linkExternal?:
          | T
          | {
              text?: T;
              href?: T;
              openInNewWindow?: T;
            };
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazineDetail_select".
 */
export interface MagazineDetailSelect<T extends boolean = true> {
  overviewPageProps?:
    | T
    | {
        teaserText?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        lead?: T;
        author?: T;
        date?: T;
      };
  contentBlocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              alignement?: T;
              image?: T;
              title?: T;
              caption?: T;
              credits?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              video?: T;
              title?: T;
              caption?: T;
              credits?: T;
              stillImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  downloads?:
    | T
    | {
        downloads?: T;
      };
  links?:
    | T
    | {
        linkExternal?:
          | T
          | {
              text?: T;
              href?: T;
              openInNewWindow?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  title: string;
  text: string;
  sideTitle: string;
  lead?: string | null;
  optionalLink?: {
    includeLink?: boolean | null;
    link?: {
      text: string;
      slug: string | Page;
      openInNewWindow?: boolean | null;
    };
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network".
 */
export interface Network {
  id: string;
  hero: {
    title: string;
  };
  filter: {
    allCheckboxText: string;
    title: string;
  };
  items: {
    foundingYearText: string;
    linkText: string;
    items: {
      title: string;
      category: string | NetworkCategory;
      foundingYear: number;
      image: string | Image;
      link: string;
      id?: string | null;
      blockName?: string | null;
      blockType: 'networkBlock';
    }[];
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion".
 */
export interface Promotion {
  id: string;
  hero: {
    title: string;
    lead: string;
  };
  subpageSections: {
    title: string;
    lead: string;
    alignement?: ('vertical' | 'horizontal') | null;
    blocks: {
      title: string;
      text: string;
      linkType: 'internal' | 'external';
      linkInternal?: {
        text: string;
        slug: string | Page;
        openInNewWindow?: boolean | null;
      };
      linkExternal?: {
        text: string;
        href: string;
        openInNewWindow?: boolean | null;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'subpageSectionBlock';
    }[];
    id?: string | null;
    blockName?: string | null;
    blockType: 'subpageSection';
  }[];
  faq: {
    faq: (string | FaqItem)[];
  };
  contact: {
    buttonText: string;
    text: string;
    title: string;
    formResponse: {
      optionalLink?: {
        includeLink?: boolean | null;
        link?: {
          text: string;
          slug: string | Page;
          openInNewWindow?: boolean | null;
        };
      };
      colorScheme: 'bright' | 'dark';
    };
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutes".
 */
export interface Institute {
  id: string;
  hero: {
    title: string;
    colorMode: 'white' | 'color';
    colorScheme?: ('bright' | 'dark') | null;
  };
  teasers: {
    teaserLinkText: string;
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "earlyCareerAward".
 */
export interface EarlyCareerAward {
  id: string;
  hero: {
    title: string;
  };
  textBlocksBefore: {
    title?: string | null;
    text: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
    blockName?: string | null;
    blockType: 'textBlock';
  }[];
  winnersTeasers: {
    buttonText: string;
  };
  textBlocksAfter: {
    title?: string | null;
    text: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
    blockName?: string | null;
    blockType: 'textBlock';
  }[];
  downloads: {
    title: string;
    downloads: (string | Document)[];
  };
  cta: {
    title: string;
    text: string;
    buttonText: string;
  };
  faq: {
    colorMode: 'white' | 'color';
    colorScheme?: ('bright' | 'dark') | null;
    faq: (string | FaqItem)[];
  };
  contact: {
    colorMode: 'white' | 'color';
    colorScheme?: ('bright' | 'dark') | null;
    contactPerson: string | Person;
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  hero: {
    title: string;
  };
  subpageSections: {
    title: string;
    lead: string;
    alignement?: ('vertical' | 'horizontal') | null;
    blocks: {
      title: string;
      text: string;
      linkType: 'internal' | 'external';
      linkInternal?: {
        text: string;
        slug: string | Page;
        openInNewWindow?: boolean | null;
      };
      linkExternal?: {
        text: string;
        href: string;
        openInNewWindow?: boolean | null;
      };
      id?: string | null;
      blockName?: string | null;
      blockType: 'subpageSectionBlock';
    }[];
    id?: string | null;
    blockName?: string | null;
    blockType: 'subpageSection';
  }[];
  magazine: {
    title: string;
    lead: string;
    link: {
      text: string;
      slug: string | Page;
      openInNewWindow?: boolean | null;
    };
  };
  publications: {
    title: string;
    lead: string;
    link: {
      text: string;
      slug: string | Page;
      openInNewWindow?: boolean | null;
    };
  };
  events: {
    title: string;
    link: {
      text: string;
      slug: string | Page;
      openInNewWindow?: boolean | null;
    };
  };
  news: {
    title: string;
    link: {
      text: string;
      slug: string | Page;
      openInNewWindow?: boolean | null;
    };
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazineOverview".
 */
export interface MagazineOverview {
  id: string;
  hero: {
    title: string;
  };
  magazineDetailPageProps: {
    heroExportButtonText: string;
    linksTitle: string;
    subscribeButtonText: string;
    downloadsTitle: string;
    downloadsText: string;
  };
  meta: {
    seo?: {
      index?: boolean | null;
      title?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Image;
      description?: string | null;
    };
    openGraph: {
      Title: string;
      Description: string;
      image: string | Image;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  sideTitle?: T;
  lead?: T;
  optionalLink?:
    | T
    | {
        includeLink?: T;
        link?:
          | T
          | {
              text?: T;
              slug?: T;
              openInNewWindow?: T;
            };
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network_select".
 */
export interface NetworkSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
      };
  filter?:
    | T
    | {
        allCheckboxText?: T;
        title?: T;
      };
  items?:
    | T
    | {
        foundingYearText?: T;
        linkText?: T;
        items?:
          | T
          | {
              networkBlock?:
                | T
                | {
                    title?: T;
                    category?: T;
                    foundingYear?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion_select".
 */
export interface PromotionSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        lead?: T;
      };
  subpageSections?:
    | T
    | {
        subpageSection?:
          | T
          | {
              title?: T;
              lead?: T;
              alignement?: T;
              blocks?:
                | T
                | {
                    subpageSectionBlock?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          linkType?: T;
                          linkInternal?:
                            | T
                            | {
                                text?: T;
                                slug?: T;
                                openInNewWindow?: T;
                              };
                          linkExternal?:
                            | T
                            | {
                                text?: T;
                                href?: T;
                                openInNewWindow?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  faq?:
    | T
    | {
        faq?: T;
      };
  contact?:
    | T
    | {
        buttonText?: T;
        text?: T;
        title?: T;
        formResponse?:
          | T
          | {
              optionalLink?:
                | T
                | {
                    includeLink?: T;
                    link?:
                      | T
                      | {
                          text?: T;
                          slug?: T;
                          openInNewWindow?: T;
                        };
                  };
              colorScheme?: T;
            };
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutes_select".
 */
export interface InstitutesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        colorMode?: T;
        colorScheme?: T;
      };
  teasers?:
    | T
    | {
        teaserLinkText?: T;
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "earlyCareerAward_select".
 */
export interface EarlyCareerAwardSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
      };
  textBlocksBefore?:
    | T
    | {
        textBlock?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  winnersTeasers?:
    | T
    | {
        buttonText?: T;
      };
  textBlocksAfter?:
    | T
    | {
        textBlock?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  downloads?:
    | T
    | {
        title?: T;
        downloads?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        buttonText?: T;
      };
  faq?:
    | T
    | {
        colorMode?: T;
        colorScheme?: T;
        faq?: T;
      };
  contact?:
    | T
    | {
        colorMode?: T;
        colorScheme?: T;
        contactPerson?: T;
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
      };
  subpageSections?:
    | T
    | {
        subpageSection?:
          | T
          | {
              title?: T;
              lead?: T;
              alignement?: T;
              blocks?:
                | T
                | {
                    subpageSectionBlock?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          linkType?: T;
                          linkInternal?:
                            | T
                            | {
                                text?: T;
                                slug?: T;
                                openInNewWindow?: T;
                              };
                          linkExternal?:
                            | T
                            | {
                                text?: T;
                                href?: T;
                                openInNewWindow?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  magazine?:
    | T
    | {
        title?: T;
        lead?: T;
        link?:
          | T
          | {
              text?: T;
              slug?: T;
              openInNewWindow?: T;
            };
      };
  publications?:
    | T
    | {
        title?: T;
        lead?: T;
        link?:
          | T
          | {
              text?: T;
              slug?: T;
              openInNewWindow?: T;
            };
      };
  events?:
    | T
    | {
        title?: T;
        link?:
          | T
          | {
              text?: T;
              slug?: T;
              openInNewWindow?: T;
            };
      };
  news?:
    | T
    | {
        title?: T;
        link?:
          | T
          | {
              text?: T;
              slug?: T;
              openInNewWindow?: T;
            };
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazineOverview_select".
 */
export interface MagazineOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
      };
  magazineDetailPageProps?:
    | T
    | {
        heroExportButtonText?: T;
        linksTitle?: T;
        subscribeButtonText?: T;
        downloadsTitle?: T;
        downloadsText?: T;
      };
  meta?:
    | T
    | {
        seo?:
          | T
          | {
              index?: T;
              title?: T;
              image?: T;
              description?: T;
            };
        openGraph?:
          | T
          | {
              Title?: T;
              Description?: T;
              image?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}