name: Branch Deployment
on:
  push:
    branches-ignore:
      - 'main'
      - 'release-please--branches--main'
jobs:
  Deploy-Branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build test container
        run: npm run docker:test:build
      - name: Test
        run: npm run test